config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'

  resources :posts, only: %i[index show new create] do
    scope module: :posts do
      resources :comments, only: :create
      resources :likes, only: %i[create destroy]
    end
  end

  match '/404', via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :name, presence: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :category
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id', inverse_of: :posts

  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy

  validates :body, length: { minimum: 50 }
  validates :title, :body, presence: true

  scope :by_recently_created, -> { order(created_at: :desc) }

  def find_like(user)
    likes.find { |like| like.user_id == user.id }
  end
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_ancestry
  validates :content, presence: true
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy
  has_many :posts, inverse_of: :creator, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
# frozen_string_literal: true

class ErrorsController < ApplicationController
  layout 'error'

  def not_found
    render status: :not_found
  end

  def unprocessable_entity
    render status: :unprocessable_entity
  end

  def server_error
    render status: :server_error
  end
end

app/controllers/posts/application_controller.rb
# frozen_string_literal: true

module Posts
  class ApplicationController < ApplicationController
    def resource_post
      @resource_post ||= Post.find params[:post_id]
    end
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

module Posts
  class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      @comment = resource_post.comments.build comment_params
      @comment.user = current_user

      if @comment.save
        redirect_to resource_post, notice: t('.success')
      else
        redirect_to resource_post, alert: @comment.errors.full_messages.first
      end
    end

    private

    def comment_params
      params.required(:post_comment).permit(:content, :parent_id)
    end
  end
end

app/controllers/posts/likes_controller.rb
# frozen_string_literal: true

module Posts
  class LikesController < ApplicationController
    before_action :authenticate_user!

    def create
      PostLike.find_or_create_by(
        post: resource_post,
        user: current_user
      )
      redirect_to resource_post
    end

    def destroy
      @like = resource_post.find_like current_user
      return if @like.blank?

      @like.destroy
      redirect_to resource_post
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @posts = Post.includes(:creator).by_recently_created
  end

  def show
    @post = Post.find params[:id]
    @user_like = @post.find_like(current_user) if current_user
    @comments = @post.comments.includes(:user).arrange
    @new_comment = PostComment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build post_params

    if @post.save
      redirect_to root_path, notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.required(:post).permit(:title, :body, :category_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def get_alert_class(flash_type)
    class_from_type = {
      notice: 'alert-success',
      alert: 'alert-danger'
    }
    "alert #{class_from_type[flash_type.to_sym]}"
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/posts/comments_helper.rb
# frozen_string_literal: true

module Posts
  module CommentsHelper
  end
end

app/helpers/posts/likes_helper.rb
# frozen_string_literal: true

module Posts
  module LikesHelper
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/layouts/application.html.slim
doctype html
html

  = render 'layouts/shared/head'

  body.d-flex.flex-column.h-100

    header
      = render 'layouts/shared/nav'

    main.flex-shrink-0
      .container.my-4

        = render 'layouts/shared/flash'

        = yield

app/views/layouts/error.html.slim
doctype html
html

  = render 'layouts/shared/head'

  body.d-flex.flex-column.h-100

    header
      = render 'layouts/shared/nav'

    main.flex-shrink-0
      .container.my-4

        = yield

app/views/layouts/shared/_flash.html.slim
- flash.each do |type, message|
  div[class=get_alert_class(type)]
    = message

app/views/layouts/shared/_head.html.slim
head
  meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
  title = t('.title')
  meta content="width=device-width,initial-scale=1" name="viewport"
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
  = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to image_tag('hexlet_logo.jpg', alt: t('.logo'), width: 30),
        root_path,
        class: 'navbar-brand me-md-4'
    ul.nav.nav-pills
      - if user_signed_in?
          li.nav-item.me-2
            p.nav-link.disabled = current_user.email
          li.nav-item.me-2
            = link_to t('.new_post'), new_post_path, class: 'nav-link link-dark'
          li.nav-item.me-2
            = link_to t('.sign_out'), destroy_user_session_path, class: 'nav-link link-dark'
      - else
          li.nav-item.me-2
            = link_to t('.sign_in'), new_user_session_path, class: 'nav-link link-dark'
          li.nav-item.me-2
            = link_to t('.sign_up'), new_user_registration_path, class: 'nav-link link-dark'

app/views/posts/_form.html.slim
h1 = t('simple_form.post.title')

= simple_form_for(@post, data: { turbo: false }) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :category
    = f.input :title
    = f.input :body, input_html: { rows: 10 }

  .form-actions
    = f.button :submit, t('simple_form.post.submit_button'), class: 'btn-primary'

app/views/posts/comments/_form.html.slim
= simple_form_for comment, url:, html: { class: custom_class }, data: { turbo: false } do |f|
  = f.input :parent_id, as: :hidden
  = f.input :content, label: false

  = f.button :submit, t('simple_form.comment.submit_button'), class: 'btn-primary'

app/views/posts/comments/_nested_comment.html.slim
- nested_comments.each do |comment, deep_nested_comments|
  .pb-2 class=(comment.depth == 1 ? 'small' : 'ms-4')
    hr.mb-2
    .mb-4
      span.me-1 = comment.user.email
      span.text-muted = time_ago_in_words comment.created_at
      p = comment.content

    hr.mb-2
    = render 'posts/comments/reply_button', comment:

    = render('posts/comments/nested_comment', nested_comments: deep_nested_comments)

app/views/posts/comments/_reply_button.html.slim
- custom_class ||= ''

div class=custom_class
  - comment_id = comment.id

  a.small.text-muted data-bs-toggle='collapse' href="#new_post_comment-#{comment_id}"
    = t('.link_text')

  .collapse data-bs-target="new_post_comment-#{comment_id}" id="new_post_comment-#{comment_id}"
    = render( \
      'posts/comments/form',
      comment: comment.children.new,
      url: post_comments_path(comment.post),
      custom_class: 'mb-4' \
    )

app/views/posts/index.html.slim
h1 = t('.title')

div
  - @posts.each do |post|
    article.card.mb-3
      .card-body
        h2.h5
          = link_to post.title,
            post,
            class: 'link-dark text-decoration-none'
        p.mb-2 = post.body.truncate_words 30

        .small.text-muted
          span.me-2 = t('.likes', count: post.likes.size)
          span.me-2 = time_ago_in_words post.created_at
          span = post.creator.email

app/views/posts/likes/_button.html.slim
span.me-2 = post.likes.size

- if like.present?
  = link_to post_like_path(post, like, format: :html),
    method: :delete,
    data: { turbo_method: :delete } \
    do
      i.bi.bi-hand-thumbs-up-fill
- else
  = link_to post_likes_path(post, format: :html),
    method: :post,
    data: { turbo_method: :post } \
    do
      i.bi.bi-hand-thumbs-up

app/views/posts/new.html.slim
== render 'form', post: @post

br

app/views/posts/show.html.slim
ol.breadcrumb
  li.breadcrumb-item
    = link_to t('.all_posts'), root_path
  li.breadcrumb-item.active
    = @post.category.name

article.mt-4
  h1.mb-lg-5 = @post.title
  = simple_format @post.body

  div class='d-flex justify-content-between mt-5'
    div
      span.me-2 = @post.creator.email
      span = time_ago_in_words @post.created_at
    div = render 'posts/likes/button', post: @post, like: @user_like

div
  p.lead.mb-3 = t('.comments')

  = render( \
    'posts/comments/form',
    comment: @new_comment,
    url: post_comments_url(@post),
    custom_class: 'mb-4' \
  )

  - @comments.each do |comment, nested_comments|
    .card.mb-4
      .card-header.mb-2.small
        span.me-2 = comment.user.email
        span = time_ago_in_words comment.created_at

      .card-body
        p.mb-3 = comment.content
        = render('posts/comments/nested_comment', nested_comments:)

      hr.my-2
      = render 'posts/comments/reply_button', comment:, custom_class: 'p-4 pb-2'